Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MvcJavaScript.Models
{
    public class Persona
    {
        public string Nombre { get; set; }
        public int Edad { get; set; }
    }
}

Controllers/AjaxController.cs
using MvcJavaScript.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcJavaScript.Controllers
{
    public class AjaxController : Controller
    {
        //
        // GET: /Ajax/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetExample() 
        {
            return View();
        }

        public ActionResult GetExampleParams()
        {
            return View();
        }
        public ContentResult SaludoHtml() //es para regresar nadamas un texto.
        {
            return Content(string.Format("<h1>{0}</h1><p>{1}</p>","hola","Este contenido fue obtenido mediante Ajax"));
        }

        public ActionResult ObtenerSaludo(string nombre, int edad) //recibe dos parametros
        {
            var objetoAnonimo = new { nombre = nombre, edad = edad };
            return Json(objetoAnonimo, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult ObtenerSaludo(Persona model)//recibe un modelo
        {
            var objetoAnonimo = new { nombre = model.Nombre, edad = model.Edad };
            return Json(objetoAnonimo, JsonRequestBehavior.AllowGet);
        }
        public ActionResult JSonExample()
        {
            return View();
        }
        public ActionResult ValidationView() 
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcJavaScript.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MyFirstJsClass()
        {
            return View();
        }
        public ActionResult EstilosJquery()
        {
            return View();
        }
        public ActionResult SelectoresJQuery()
        {
            return View();
        }
        public ActionResult EventosJQuery()
        {
            return View();
        }
        public ActionResult TiposDeClases()
        {
            return View();
        }
    }
}

Views/Ajax/GetExample.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
    <div id="content"></div>

      <input type="hidden" id="url" value="@Url.Action("SaludoHtml","Ajax")" />

      <input type="button" id ="saludo" value="Obtener Saludo" />

    <a href="@Url.Action("Index","Home")">Regresar</a>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/jquery-2.1.1.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/GetExample.js")"></script>
  </body>
</html>

Views/Ajax/GetExampleParams.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
    <div id="content"></div>

    <input type="hidden" id="url" value="@Url.Action("ObtenerSaludo","Ajax")" />
    Nombre: <input type="text" id="nombre"/> <br />
    Edad: <input type="text" id="edad"/>

    <input type="button" id ="saludo" value="Obtener Saludo" />

    <a href="@Url.Action("Index","Home")">Regresar</a>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/jquery-2.1.1.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/GetExampleParams.js")"></script>
  </body>
</html>

Views/Ajax/Index.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
    <ul>
        <li>
            <a href="@Url.Action("GetExample","Ajax")">Get Example</a>
        </li>

        <li>
            <a href="@Url.Action("GetExampleParams","Ajax")">Get Example enviando parametros</a>
        </li>

        <li>
            <a href="@Url.Action("JSonExample","Ajax")">JSonExample</a>
        </li>
    </ul>
  </body>
</html>

Views/Ajax/JSonExample.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
    <div id="content"></div>

    <input type="button" id ="saludo" value="Obtener Saludo" />

    <a href="@Url.Action("Index","Home")">Regresar</a>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/jquery-2.1.1.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/JSonExample.js")"></script>
  </body>
</html>

Views/Ajax/ValidationView.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Validation</title>
      <style>
	        form {
		        width: 500px;
	        }
	        form label {
		        width: 250px;
	        }
	        form label.error, form input.submit {
		        margin-left: 50px;
                color:red;
	        }
	</style>
  </head>
  <body>
    <form method="post" action="">
        <fieldset>
            <legend>Hola</legend>
            <p>
                <label for="nombre">Nombre</label>
                <input type="text" id="nombre" name="nombre" data-rule-required="true" />
            </p>
            <p>
                <label for="edad">Edad</label>
                <input type="number" id="edad" />
            </p>
            <input type="submit" class="submit" value="Guardar" />
        </fieldset>
    </form>
       <a href="@Url.Action("Index","Home")">Regresar</a>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/jquery-2.1.1.min.js")"></script>
      <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.js"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/Validation.js")"></script>
  </body>
</html>

Views/Home/EstilosJquery.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
    <div id="persona">
        <span id="nombre">Jonas</span>
        <br />
        <span id="edad">28</span>
        <br />
        <span id="calificacion">8</span>
    </div>
    <a href="@Url.Action("Index","Home")">Regresar</a>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/jquery-2.1.1.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/JonasJquery.js")"></script>

  </body>
</html>

Views/Home/EventosJQuery.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
    
    <div id="eventosLog">
    </div>

    <div class="mouseListener" style="border:1px solid yellow; height:200px; width:200px;">
    </div>

    <input type="text" name="x" />
    <input type="text" name="y" />

      <ul>
          <li>Jonas</li>
          <li>Nahum</li>
          <li class="fade">Jimenez</li>
          <li class="fade">Garcia</li>
      </ul>

    <input type="button" value="Mybutton" />
      
    <a href="@Url.Action("Index","Home")">Regresar</a>

    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/jquery-2.1.1.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/EventosJQuery.js")"></script>

  </body>
</html>

Views/Home/Index.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
    
    <article>
        <header>
            <h1>Clase Java Script</h1>
        </header>
        <p>
            En esta pagina se cra una clase de java script para poner
            estilos a un objeto Html. Esta clase existe dentro del
            namespace Jonas.
        </p>
        <p>
            <a href="@Url.Action("MyFirstJsClass","Home")">MyFirstJsClass</a>
        </p>
    </article>

    <article>
        <header>
            <h1>Estilos con Jquery($)</h1>
        </header>
        <p>
            En esta pagina dan los mismos estilos que con la clase anterior pero 
            usando jquery.
        </p>
        <p>
            <a href="@Url.Action("EstilosJquery","Home")">Estilos Jquery</a>
        </p>
    </article> 

    <article>
        <header>
            <h1>Selectores con JQuery</h1>
        </header>
        <p>
            Este es un ejercicio de algunos selectores de JQuery
        </p>
        <p>
            <a href="@Url.Action("SelectoresJQuery","Home")">Selectores $</a>
        </p>
    </article>    

    <article>
        <header>
            <h1>Eventos JQuery</h1>
        </header>
        <p>
            Este es un ejercicio de algunos eventos de JQuery
        </p>
        <p>
            <a href="@Url.Action("EventosJQuery","Home")">Eventos $</a>
        </p>
    </article>   
    
      <article>
        <header>
            <h1>Tipos De Clases</h1>
        </header>
        <p>
            Tipos de clases de JavaScript, clases anonimas, con function y con array.
        </p>
        <p>
            <a href="@Url.Action("TiposDeClases","Home")">Tipos De Clases</a>
        </p>
    </article>


       <article>
        <header>
            <h1>Ajax</h1>
        </header>
        <p>
            Ajax
        </p>
        <p>
            <a href="@Url.Action("Index","Ajax")">Ajax</a>
        </p>
    </article>

  </body>
</html>

Views/Home/MyFirstJsClass.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
    <div id="persona">
        <span id="nombre">Jonas</span>
        <br />
        <span id="edad">28</span>
        <br />
        <span id="calificacion">8</span>
    </div>
    <a href="@Url.Action("Index","Home")">Regresar</a>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/Jonas.js")"></script>
  </body>
</html>

Views/Home/SelectoresJQuery.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
      <h1>Esta pagina describe</h1>
      <h2>Los selectores de JQuery</h2>
      <article>
          <header>
              <h1>Selectores</h1>
          </header>
          <h2>id #</h2>
          <p class="textoazul">
              El selector de Id es el signo de #
              por ejemplo para seleccionar <span id="spanId">Este span</span>
              usamos $("#spanId"); y para subrayarlo usariamos $("#spanId").ccs("text-decoration","underline");
          </p>

          <h2>selector de html tag</h2>
          <p>
              Para seleccionar todos (un array de elementos html) los elementos de un tipo
              simplemente ponemos entre comillas el nombre del tag deseado
              por ejemplo: para ponerle borde a todos los parrafos usariamos
              $("p").css("border","1px solid black");
          </p>

          <h2>selector de propiedad class usando signo de punto </h2>
          <p>
              Para seleccionar todos los elementos html que usan una clase se usa 
              el punto seguido de el nombre de la clase por ejemplo
              $(".textoazul").css("color","blue"); pondra letras en color
              azul a todos los tags de html que tengan la propiedad class="textoazul"
              <span class="textoazul">tiene clase textoazul</span>
              <span class="textorojo">tiene clase textorojo</span>
          </p>
          
          <h2>selector de cualquier propiedad igual a un valor dado </h2>
          <p>
              Para seleccionar todos los elementos cuya propiedad sea igual a un valor dado
              por ejemplo, si quisieramos seleccionar todos los elementos cuya propiedad
              name sea igual a myname, usariamos los [] de la siguiente manera
              $("[name='myname']").css("color","red");
             <input type="text" name="myname" value="input name='myname'" /> 
          </p>
      </article>


    <a href="@Url.Action("Index","Home")">Regresar</a>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/jquery-2.1.1.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/SelectoresJQuery.js")"></script>

  </body>
</html>

Views/Home/TiposDeClases.cshtml
<!DOCTYPE HTML>
<html>
  <head>
    <title>Titulo</title>
  </head>
  <body>
    <div id="persona">
        
    </div>
    <a href="@Url.Action("Index","Home")">Regresar</a>
    <script type="text/javascript" src="@Url.Content("~/Scripts/Jonas/TiposDeClases.js")"></script>
  </body>
</html>